### ISSUE TITLE
Adicionar campo para data de ultima atualização

### ISSUE THREAD

**Issue by ellergus** [gabrielfurlan-dev/weekly-report#10]
# Critérios de aceitação: 
-Adicionar nova label informando a hora ou data da última atualização.

# Protótipo:

![Image](https://github.com/gabrielfurlan-dev/weekly-report/assets/121299465/65ffb9d6-253a-4788-9742-3c99ec76a6f4)

**Comment by GabrielGarcia190** [comment]
@ellergus  favor anexar as imagens do protótipo
