### ISSUE TITLE
Cor de texto inalterada após troca entre Tema Escuro e Tema Claro

### ISSUE THREAD

**Issue by guto-dev** [gabrielfurlan-dev/weekly-report#14]
Passo 1: Selecione a aba de Relatórios
![image](https://github.com/gabrielfurlan-dev/weekly-report/assets/130815783/6f478a83-3da6-4851-ae7d-33f0fb39722c)

Passo 2: Selecione um relatório que não possua "Goals" na seção de "Check List"
![image](https://github.com/gabrielfurlan-dev/weekly-report/assets/130815783/95f95b70-d64a-4fba-8366-e548336f3e36)

Passo 3: Troque o tema de Claro para Escuro
![Sem título](https://github.com/gabrielfurlan-dev/weekly-report/assets/130815783/a0a91a67-bd45-4145-9728-c0d79c797527)

Issue: No tema escuro, o texto permanece na cor preta
![Sem título](https://github.com/gabrielfurlan-dev/weekly-report/assets/130815783/d6e5ce0d-2e4a-4bec-877c-f492e372429f)

## Critérios de Aceitação
1. Ao alterar o tema de claro para escuro visualizando um relatório que não seja seu, o texto "Sem metas de check" deve mudar sua cor para branca;
2. Apresentar "Loading" ao carregar relatórios.

**Comment by gabrielfurlan-dev** [comment]
Pull request aprovado
