### ISSUE TITLE
Corrigir data sendo apresentada com uma barra indevida

### ISSUE THREAD

**Issue by GabrielGarcia190** [gabrielfurlan-dev/weekly-report#31]
![Image](https://user-images.githubusercontent.com/79483921/265010972-a0c78c42-8e40-4735-b0e1-fcf3de132819.png)

**Comment by gabrielfurlan-dev** [comment]
@GabrielGarcia190 conversei com o [@Donato Junior](https://github.com/odonatojunior) sobre a questão de traduzir as páginas para o idioma de origem do usuário.

Ele comentou sobre a utilização de uma biblioteca chamada i18n, porém no cenário atual, será melhor manter o idioma e as padronizações de dados (data e moeda) em português do Brasil.

Posteriormente, se houver a necessidade de disponibilizar em mais idiomas, implementaremos utilizando a biblioteca citada ou outra que possa nos atender melhor.
